# Generated by Django 4.2.6 on 2023-12-21 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gastosdiarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('gasto', models.IntegerField()),
            ],
            options={
                'db_table': 'gastosdiarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ventadiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('precioventa', models.IntegerField(db_column='precioVenta')),
                ('ventatanque', models.CharField(blank=True, db_column='ventaTanque', max_length=255, null=True)),
            ],
            options={
                'db_table': 'ventadiaria',
                'managed': False,
            },
        ),
    ]
